services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"   # specify the exact Python version here
